CORRECTION_EQUAL = 0
CORRECTION_SMALLER = 1
CORRECTION_BIGGER = 2
CORRECTION_INCOMPARABLE = -1

EDIT_OPERATION_READ_SYMBOL = "READ "
EDIT_OPERATION_REPLACE_SYMBOL1 = "REPLACE "
EDIT_OPERATION_REPLACE_SYMBOL2 = " BY "
EDIT_OPERATION_DEL_SYMBOL = "DEL "
EDIT_OPERATION_INS_SYMBOL = "INS "
